[workspace]
members = [
    "datafusion-optd-cli",
    "optd-core",
    "optd-datafusion-bridge",
    "optd-datafusion-repr",
    "optd-sqlplannertest",
    "optd-adaptive-demo",
    "optd-gungnir",
    "optd-perfbench",
    "optd-datafusion-repr-adv-cost",
    "optd-sqllogictest",
]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"
homepage = "https://github.com/cmu-db/optd"
keywords = ["sql", "database", "optimizer", "datafusion"]
license = "MIT"
repository = "https://github.com/cmu-db/optd"
