[package]
name = "optd-sqlplannertest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
anyhow = { version = "1", features = ["backtrace"] }
sqlplannertest = { git = "https://github.com/risinglightdb/sqlplannertest-rs", branch = "main" }
async-trait = "0.1"
datafusion-optd-cli = { path = "../datafusion-optd-cli" }
# optd-datafusion-repr-adv-cost = { path = "../optd-datafusion-repr-adv-cost" }
datafusion = { version = "32.0.0", features = [
    "avro",
    "crypto_expressions",
    "encoding_expressions",
    "regex_expressions",
    "unicode_expressions",
    "compression",
] }
env_logger = "0.9"
mimalloc = { version = "0.1", default-features = false }
regex = "1.8"
tokio = { version = "1.24", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
    "parking_lot",
] }
optd-datafusion-bridge = { path = "../optd-datafusion-bridge" }
optd-datafusion-repr = { path = "../optd-datafusion-repr" }
itertools = "0.11"
lazy_static = "1.4.0"

[[test]]
name = "planner_test"
harness = false
